apiVersion: v1
kind: Pod
metadata:
  name: debian-pod
  namespace: default
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: debian-container
    image: debian:latest
    command: ["/bin/bash", "-c"]
    args:
      - |
        apt-get update && \
        apt-get install -y fio curl git tmux && \
        while true; do sleep 3600; done
    volumeMounts:
    - name: cephfs-volume
      mountPath: /mnt/ceph
    - name: rbd-volume
      mountPath: /mnt/rbd
    - name: proxmox-volume
      mountPath: /mnt/proxmox
  volumes:
  - name: cephfs-volume
    persistentVolumeClaim:
      claimName: cephfs-pvc
  - name: rbd-volume
    persistentVolumeClaim:
      claimName: rbd-pvc
  - name: proxmox-volume
    persistentVolumeClaim:
      claimName: proxmox-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc
  namespace: default
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-pvc
  namespace: default
spec:
  storageClassName: ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proxmox-pvc
  namespace: default
spec:
  storageClassName: proxmox-lvm
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
